CREATE TABLE usuario (pk INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
    nome VARCHAR(50),
    email VARCHAR(50)
);

CREATE TABLE obra (pk INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
    titulo VARCHAR(100),
    id_artista int
);

CREATE TABLE emprestimo (pk INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
    id_obra int,
    id_usuario int
);

CREATE TABLE artista (pk INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
    nome VARCHAR(50)
);


ALTER TABLE obra ADD FOREIGN KEY (id_artista) REFERENCES artista(pk);
ALTER TABLE emprestimo ADD FOREIGN KEY (id_obra) REFERENCES obra(pk);
ALTER TABLE emprestimo ADD FOREIGN KEY (id_usuario) REFERENCES usuario(pk);




